# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root  # Substitua 'root' pelo nome de usuário do MySQL que você configurou
  password: senha  # Substitua 'senha' pela senha que você configurou
  host: localhost

development:
  <<: *default
  database: car_listing_app_development  # Substitua pelo nome do seu banco de dados de desenvolvimento

test:
  <<: *default
  database: car_listing_app_test  # Substitua pelo nome do seu banco de dados de teste

production:
  <<: *default
  database: car_listing_app_production  # Substitua pelo nome do seu banco de dados de produção
  username: car_listing_app  # Substitua pelo nome de usuário do MySQL para produção
  password: <%= ENV['CAR_LISTING_APP_DATABASE_PASSWORD'] %>  # Use a variável de ambiente para a senha de produção
